apiVersion: autoscaling/v1
kind: HorizontalPodAutoscalar
metadata:
  name: nodeapp-autoscale
spec:
  maxReplicas: 20
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp-deployment
  targetCPUUtilizationPercentage: 50

    
      